/*
 - String has one function String(char[].int a,int b) this functin will give string of string generated by concatening the char array elements ranging from int a to int b .
  - when we only pass the array of int datatype then there is  give error because there is not a constructor .
   -when we passed a single  int array address then there will come error as there is not a constructor whose arguement is single int array 
   -     
 */
class COre2web{
	public static void main(String[] args){
		char[] arr={'7','8','9','0','d','2'};
		String str=new String(arr,2,4);
		String str1=str.copyValueOf(arr);
		System.out.println(str1);
		System.out.println(arr);
	}
}

